### ISSUE TITLE
Structure visualizer doesn't appears if expression-bodied properties are present

### ISSUE THREAD

**Issue by Alcatraz3222** [Microsoft/VS-PPT#59]
![927c021a59444bd9a555bc085047bbca](https://cloud.githubusercontent.com/assets/10264083/18411534/7bdaf76a-7779-11e6-8547-915df851e561.png)

![fcfd91f4ee3246f68f300330f8985137](https://cloud.githubusercontent.com/assets/10264083/18411547/bafbb0ec-7779-11e6-9d8e-9e1548379ce9.png)

I just realized it doesn't appear if you use expresion-bodied properties, it doesn't happend with expresion-bodied methods though.

**Comment by iobus** [comment]
I am having this issue as well.  Since I have started using them in VS2015 this bug is quite annoying.

**Comment by tripplet** [comment]
This was fixed in f3c907144b625acb01be3ab548724701e3121f75
Could we get an new release as this bug is really annoying.

**Comment by booman** [comment]
I'm still having the same issue, when it is going to be fixed?

**Comment by tripplet** [comment]
I compiled the plugin myself and it seems to work for me. The downside is the "normal" PowerTools contains some additional plugins which are not present in the github repo so you can't really replace it.
Also replacing the necessary dlls in the original vsix package didn't work for me as there where some issues.
My approach was to remove the StructureVisualizer from the original vsix archive and install the patched StructureVisualizer as a separat plugin.
Not the best solution but works for me until there is a new official version.

Feel free to use my precompiled version or follow the steps above.
[VS-PPT-Patched.zip](https://github.com/Microsoft/VS-PPT/files/654640/VS-PPT-Patched.zip)

**Comment by MikeWilliams-UK** [comment]
Which of the "normal" PowerTools are missing?

**Comment by tripplet** [comment]
I don't remember all dlls which were missing, but if you compile this repository yourself, some dlls are not generated which are present in the original vsix packet.

ToggleDockHeader.dll for example in inside the original vsix but not generated.
But these dlls are referenced other stuff you compile which will not work as they expect other dll's therefor replacing only some dlls inside the vsix file does not work (See my previous post).
